language: c

env:
  global:
    - TARGET=k1-elf
    - PREFIX=$PWD/prefix
    - PARALLEL_JOBS=-j1

compiler:
  - gcc

os:
  - linux

install:
  - sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev texinfo

before_script:
  - git clone --depth 1 -b coolidge https://github.com/kalray/gdb-binutils.git
  - git clone --depth 1 -b coolidge https://github.com/kalray/newlib.git
  - git clone --depth 1 -b coolidge https://github.com/kalray/gcc.git

  - mkdir build-binutils
  - cd build-binutils
  - ../gdb-binutils/configure --prefix=$PREFIX --target=$TARGET --disable-initfini-array --disable-gdb --without-gdb --disable-werror --with-expat=yes --with-babeltrace=no --with-bugurl=no
  - make all $PARALLEL_JOBS
  - make install

  - cd -
  - mkdir build-gcc
  - cd build-gcc
  - ../gcc/configure --prefix=$PREFIX --target=$TARGET  --with-gnu-as --with-gnu-ld --disable-bootstrap --disable-shared --enable-multilib --disable-libmudflap --disable-libssp --enable-__cxa_atexit --with-bugurl=no --with-newlib                      --disable-libgomp --disable-libatomic --disable-threads --enable-languages=c --with-system-zlib
  - make all-gcc $PARALLEL_JOBS
  - make install-gcc


#  - mkdir $GCC_BUILD_DIR
#  - cd $GCC_BUILD_DIR && ../gcc/configure --disable-multilib --disable-bootstrap --enable-languages=c && make -j8

script:
  - echo OK
